# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=(web.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
            },
            bases=(web.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('for_date', models.DateField(verbose_name='Order For Date')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Child', verbose_name='Child')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-id',),
            },
            bases=(web.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderConfirmationId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cfm', models.PositiveIntegerField(verbose_name='Order Confirmation')),
                ('other_order_cfm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Order Confirmation')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Paid ?')),
            ],
            options={
                'verbose_name': 'OrderConfirmationId',
                'verbose_name_plural': 'OrderConfirmationIds',
            },
            bases=(web.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', localflavor.us.models.PhoneNumberField(verbose_name='Cell Phone')),
                ('home_phone', localflavor.us.models.PhoneNumberField(blank=True, null=True, verbose_name='Home Phone')),
                ('work_phone', localflavor.us.models.PhoneNumberField(blank=True, null=True, verbose_name='Work Phone')),
                ('is_membership_paid', models.BooleanField(default=False, verbose_name='Membership Paid')),
                ('gets_free_meal', models.BooleanField(default=False, verbose_name='Receives Free Meal')),
                ('gets_reduced_price_meal', models.BooleanField(default=False, verbose_name='Receives Reduced Price Meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Parent's Name")),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
            },
            bases=(web.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires At')),
                ('available_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednessday'), (3, 'Thursday'), (4, 'Friday'), (9, 'Every Week Day')], default=9, verbose_name='Day Available')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=(web.models.ModelSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='order',
            name='order_cfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.OrderConfirmationId', verbose_name='Order Confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product', verbose_name='Product'),
        ),
    ]
