# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='is_membership_paid',
            field=models.BooleanField(default=False, verbose_name='Membership Paid'),
        ),
    ]
